### PR TITLE
Fix phpstan problems

### LINKED ISSUE #45: Fix CS and static analysis
If you have a bit of time, please fix the tests.
See CI output for details.

Thank you!

### PR DESCRIPTION
**Pull request by monojp**
Tested manually via Composer VCS require

Fixes #45

### CODE REVIEW

File: src/WpThemeMagicPropertiesClassReflectionExtension.php [hunk 1]
```diff
@@ -31,6 +31,6 @@ public function hasProperty(ClassReflection $classReflection, string $propertyNa
     // phpcs:ignore SlevomatCodingStandard.Functions.UnusedParameter
     public function getProperty(ClassReflection $classReflection, string $propertyName): PropertyReflection
     {
-        return new DummyPropertyReflection();
+        return new DummyPropertyReflection(); // @phpstan-ignore-line ignore that this is not covered by BC
```
Comment (szepeviktor) [inline src/WpThemeMagicPropertiesClassReflectionExtension.php:34]:
```suggestion
        // @phpstan-ignore-next-line This is not covered by BC.
        return new DummyPropertyReflection();
```

Comment (szepeviktor) [reply src/WpThemeMagicPropertiesClassReflectionExtension.php:34]: What is the real solution instead of `DummyPropertyReflection`?

Comment (monojp) [reply src/WpThemeMagicPropertiesClassReflectionExtension.php]: I don't know unfortunately, my knowledge of phpstan internals/extensions is unfortunately very limited too. Maybe it can be adapted in a follow-up

I force-pushed and adapted the ignore

**Comment by szepeviktor** [comment]
This is a gift to me, Martin.
Thank you!
